# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aktivne senzorske table za decu
author: >-
  Autori su ljudi koji se okupljaju oko 18h uglavnom da cuju price Vucija i Stankele
description: >- # this means to ignore newlines until "baseurl:"
  Aktivne table za decu, od prve do sedme godine, omogućavaju detetu da razvija
  svoje motoričke veštine. Mogućnost biranja elemenata vam obezbeđuje da je vaša
  tabla unikatna i jedinstvena za vaše dete. Postoji mogućnost i iznajmljivanja
  na određeni period.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aktivne-table-za-decu.trk.in.rs" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-36706408-5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
